import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, '.data');
const STATE_FILE = path.join(DATA_DIR, 'state.json');
fs.mkdirSync(DATA_DIR, { recursive: true });

const envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) for (const line of fs.readFileSync(envFile,'utf8').split(/\r?\n/)) { const m=line.match(/^([A-Z0-9_]+)=(.*)$/); if(m && !process.env[m[1]]) process.env[m[1]]=m[2].trim(); }

const SOURCES = [
 ['OpenAI','https://openai.com/news/rss.xml'],['Google AI','https://blog.google/technology/ai/rss/'],
 ['Hugging Face','https://huggingface.co/blog/feed.xml'],['The Hacker News','https://feeds.feedburner.com/TheHackersNews'],
 ['Krebs on Security','https://krebsonsecurity.com/feed/'],['Google Security','https://security.googleblog.com/feeds/posts/default'],
 ['NVIDIA Developer','https://developer.nvidia.com/blog/feed/']
];
const DEFAULT_PERSONA={name:'CyberForge',domain:'AI Security',description:'An autonomous AI security researcher tracking practical risks and engineering lessons in AI systems.',interests:['AI agent security','MCP security','prompt injection','LLM vulnerabilities','AI infrastructure','model security','AI supply chain'],voice:'sharp, technical, concise, practical, evidence-first',audience:'AI engineers, security researchers, and developers building production AI systems'};
const initial=()=>({agentId:null,persona:null,initializedAt:null,posts:[],rejected:[],lastDiscoveryAt:null,lastPublishAt:null,runCount:0});
let state=(()=>{try{return JSON.parse(fs.readFileSync(STATE_FILE,'utf8'))}catch{return initial()}})();
const save=()=>fs.writeFileSync(STATE_FILE,JSON.stringify(state,null,2));
const uid=prefix=>`${prefix}_${crypto.randomUUID()}`;
const clean=s=>(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
const esc=s=>clean(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const hours=d=>(Date.now()-new Date(d).getTime())/36e5;
function tag(xml,name){const m=xml.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)</${name}>`,'i'));return m?clean(m[1]):''}
function parseItems(xml){const blocks=[...xml.matchAll(/<(?:item|entry)(?:\s[^>]*)?>([\s\S]*?)<\/(?:item|entry)>/gi)].map(m=>m[1]);return blocks.map(b=>{const title=tag(b,'title'), linkMatch=b.match(/<link[^>]*href=["']([^"']+)["'][^>]*>/i), link=linkMatch?linkMatch[1]:tag(b,'link'), summary=tag(b,'description')||tag(b,'summary')||tag(b,'content'), date=tag(b,'pubDate')||tag(b,'published')||tag(b,'updated');return {title,link,summary,publishedAt:date||new Date().toISOString()}}).filter(x=>x.title&&x.link)}
async function fetchText(url){const r=await fetch(url,{headers:{'user-agent':'CyberForge/1.0'},signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.text()}
async function discover(){const out=[];await Promise.allSettled(SOURCES.map(async([source,url])=>{try{const xml=await fetchText(url);for(const x of parseItems(xml).slice(0,10)){const text=`${x.title} ${x.summary}`.toLowerCase();let score=35;for(const k of state.persona.interests)if(text.includes(k.toLowerCase()))score+=9;if(/security|vulnerab|exploit|agent|mcp|prompt injection|llm|model|ai|inference/.test(text))score+=18;if(hours(x.publishedAt)<=24)score+=15;else if(hours(x.publishedAt)<=72)score+=7;if(text.length<80)score-=15;if(/sponsored|webinar|job opening|subscribe/.test(text))score-=20;out.push({...x,source,score:Math.max(0,Math.min(100,score))})}}catch{}}));return out.sort((a,b)=>b.score-a.score)}
function duplicate(title){const ws=clean(title).toLowerCase().split(/\W+/).filter(w=>w.length>3);return state.posts.some(p=>ws.filter(w=>p.sourceTitle.toLowerCase().includes(w)).length>=Math.max(3,Math.ceil(ws.length*.55)))}
function fallback(t){return `${t.title}\n\n${t.summary?esc(t.summary).slice(0,220)+'. ':''}For teams shipping AI systems, the engineering question is not only whether the model works. It is whether the surrounding system stays trustworthy when inputs, tools, and dependencies behave unexpectedly.\n\nMy takeaway: treat this as a systems problem. Test the boundary, log the decision path, and make failure modes observable before calling the feature production-ready.\n\n— ${state.persona.name}`}
async function gemini(t){if(!process.env.GEMINI_API_KEY)return fallback(t);const prompt=`You are ${state.persona.name}, an autonomous ${state.persona.domain} researcher. Voice: ${state.persona.voice}. Audience: ${state.persona.audience}. Interests: ${state.persona.interests.join(', ')}. Write one original 90-170 word professional social post about this source. Do not invent facts. Start with a strong observation, explain why engineers should care, then give one practical takeaway. Source title: ${t.title}. Source summary: ${t.summary}. URL: ${t.link}`;try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(process.env.GEMINI_MODEL||'gemini-2.0-flash')}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.65,maxOutputTokens:500}}),signal:AbortSignal.timeout(20000)});if(!r.ok)return fallback(t);const d=await r.json();return d?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('').trim()||fallback(t)}catch{return fallback(t)}}
async function cycle(reason){if(!state.agentId)return;state.runCount++;state.lastDiscoveryAt=new Date().toISOString();const topics=await discover();const threshold=Number(process.env.MIN_TOPIC_SCORE||60);const t=topics.find(x=>x.score>=threshold&&!duplicate(x.title));if(!t){state.rejected.push({at:new Date().toISOString(),reason:'No topic met editorial threshold or all strong topics were already covered.',inspected:topics.slice(0,5).map(x=>({title:x.title,score:x.score}))});state.rejected=state.rejected.slice(-50);save();return}const post={id:uid('p'),createdAt:new Date().toISOString(),text:await gemini(t),sourceTitle:t.title,rationale:`Selected because it scored ${t.score}/100 against ${state.persona.name}'s editorial rules: strong relevance to ${state.persona.domain}, practical engineering impact, and timely coverage. Lower-scoring or previously covered candidates were rejected to avoid repetitive publishing.`,sources:[t.link],topicScore:t.score,discoverySource:t.source,trigger:reason};state.posts.unshift(post);state.posts=state.posts.slice(0,200);state.lastPublishAt=post.createdAt;save()}
function json(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(body)}
function serve(res,file){const ext=path.extname(file),types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.json':'application/json'};try{res.writeHead(200,{'content-type':types[ext]||'application/octet-stream'});res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end('Not found')}}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,initialized:Boolean(state.agentId),uptimeSeconds:Math.round(process.uptime()),posts:state.posts.length});if(req.method==='POST'&&u.pathname==='/api/agent/init'){if(state.agentId)return json(res,200,{agentId:state.agentId});let body='';for await(const c of req)body+=c;let incoming={};try{incoming=JSON.parse(body).persona||{}}catch{}state.persona={...DEFAULT_PERSONA,...incoming,interests:Array.isArray(incoming.interests)&&incoming.interests.length?incoming.interests:DEFAULT_PERSONA.interests};state.agentId=uid('agent');state.initializedAt=new Date().toISOString();save();cycle('initialization').catch(console.error);return json(res,200,{agentId:state.agentId})}if(req.method==='GET'&&u.pathname==='/api/agent/feed'){if(!state.agentId||u.searchParams.get('agentId')!==state.agentId)return json(res,404,{posts:[]});return json(res,200,{posts:state.posts.map(({id,createdAt,text,rationale,sources})=>({id,createdAt,text,rationale,sources}))})}if(req.method==='GET'&&u.pathname==='/api/agent/status')return json(res,200,{agentId:state.agentId,persona:state.persona,initializedAt:state.initializedAt,lastDiscoveryAt:state.lastDiscoveryAt,lastPublishAt:state.lastPublishAt,runCount:state.runCount,rejectedCount:state.rejected.length,postCount:state.posts.length});const publicPath=path.join(__dirname,'public',u.pathname==='/'?'index.html':u.pathname);if(u.pathname.startsWith('/api/'))return json(res,404,{error:'Not found'});serve(res,publicPath)});
const port=Number(process.env.PORT||3000);server.listen(port,()=>console.log(`CyberForge listening on :${port}`));const interval=Math.max(5,Number(process.env.PUBLISH_INTERVAL_MINUTES||30))*60000;setTimeout(()=>cycle('scheduled').catch(console.error),15000);setInterval(()=>cycle('scheduled').catch(console.error),interval);
